// Auto-generated by scripts/build_week1_offline.py. Do not edit manually.
window.__LL_I18N__ = Object.assign({}, window.__LL_I18N__ || {}, {
  "lv": {
    "html": {
      "title": "B1 LV→EN: Match Rush + Prefix Forge"
    },
    "badge": "Week 1",
    "gameTitle": "LV→EN Vārdu Spēles (B1)",
    "buttons": {
      "modeMatch": "▶ Match Rush",
      "modeForge": "▶ Prefix Forge",
      "practice": "Praktizēties",
      "challenge": "Izaicinājums",
      "prevAria": "Iepriekšējā kartīte",
      "nextAria": "Nākamā kartīte",
      "deckSizeAria": "Pārslēgt kavas izmēru",
      "deckSizeTitle": "Pārslēgt kavas izmēru",
      "export": "Eksportēt rezultātus (CSV)",
      "exportAria": "Eksportēt rezultātus CSV formātā",
      "help": "Palīdzība",
      "helpAria": "Palīdzība"
    },
    "labels": {
      "loading": "Ielādē...",
      "loadError": "Neizdevās ielādēt datus.",
      "legend": "<b>Vadība:</b> Pelē klikšķi. — <span class=\"kbd\">H</span> palīdzība, <span class=\"kbd\">R</span> atsākt raundu, <span class=\"kbd\">1</span> Match, <span class=\"kbd\">2</span> Forge, <span class=\"kbd\">D</span> kavas izmērs. <br/>📏 = Pielāgot ekrānam (bez ritināšanas), 📜 = Pilna kava (ar ritināšanu). LV→EN only.",
      "languageSelect": "Izvēlies valodu",
      "controls": "Spēles vadības",
      "gameState": "Spēles stāvoklis"
    },
    "status": {
      "ready": "Gatavs. Izvēlies režīmu.",
      "practice": "Practice režīms",
      "challenge": "Challenge režīms (Match = ♥♥♥)",
      "fit": "Fit to screen mode",
      "full": "Full deck mode (scrollable)"
    },
    "deckSize": {
      "titleAuto": "Switch to full deck (scrollable)",
      "titleFull": "Switch to fit screen (no scroll)"
    },
    "help": {
      "title": "Palīdzība",
      "close": "Aizvērt",
      "lines": [
        "▶ MATCH RUSH — Klikšķini pāri: vispirms LV vārds, tad tā EN nozīme.",
        "Kļūdas praksē rāda īsu skaidrojumu (piem., -ties = refleksīvs).",
        "Challenge režīmā ir taimeris un sirdis.",
        "",
        "📏 Deck Size — Pārslēdz starp 'fit screen' (bez ritināšanas)",
        "un 'full deck' (ar ritināšanu, vairāk vārdu).",
        "",
        "▶ PREFIX FORGE — Pievieno pareizo priedēkli pie verbu saknes",
        "(piem., __mainīt → izmainīt) pēc dotās EN nozīmes.",
        "",
        "Īsceļi: [1] Match, [2] Forge, [H] help, [R] restart, [D] deck size."
      ]
    },
    "endingsBuilder": {
      "title": "Galotņu veidotājs",
      "subtitle": "Nomet pareizo galotni, lai pabeigtu vārdu.",
      "buttons": {
        "check": "Pārbaudīt (Enter)",
        "next": "Nākamais (N)",
        "rule": "Rādīt noteikumu",
        "ruleHide": "Slēpt noteikumu",
        "report": "Ziņot par kļūdu"
      },
      "labels": {
        "score": "Rezultāts",
        "streak": "Sērija",
        "strict": "Stingrais režīms",
        "answer": "Ieraksti pilno formu",
        "keypad": "Latviešu burti",
        "options": "Galotnes",
        "dropPlaceholder": "Nomet galotni",
        "ruleTitle": "Noteikumu tabula",
        "case": "Locījums",
        "number": "Skaitlis",
        "columns": {
          "SG": "Viensk.",
          "PL": "Daudzsk.",
          "SG_M": "Vsk. vīr.",
          "SG_F": "Vsk. siev.",
          "PL_M": "Dsk. vīr.",
          "PL_F": "Dsk. siev."
        }
      },
      "feedback": {
        "correct": "Pareizi!",
        "incorrect": "Nepareizi — paskaties noteikumu.",
        "fallback": "Pieņēmu formu bez diakritiskajām zīmēm. Ieslēdz stingro režīmu, lai tās vingrinātu."
      },
      "icons": {
        "correct": "✔️",
        "incorrect": "✖️",
        "info": "ℹ️"
      },
      "announce": {
        "correct": "Pareiza galotne ievietota.",
        "incorrect": "Nepareiza galotne. Mēģini vēlreiz."
      },
      "explain": {
        "prefix": "⇒"
      },
      "strictMode": {
        "on": "Stingrais režīms ieslēgts.",
        "off": "Stingrais režīms izslēgts."
      },
      "reportTemplate": "### Kas notika?\n\nApraksti kļūdaino galotni vai noteikumu.\n\n### Konteksts\n- Sakne: (ieraksti)\n- Locījums/skaitlis: (ieraksti)\n- Ierīce/pārlūks: \n",
      "cases": {
        "NOM": "Nominatīvs",
        "GEN": "Ģenitīvs",
        "DAT": "Datīvs",
        "ACC": "Akuzatīvs",
        "LOC": "Lokatīvs",
        "VOC": "Vokatīvs"
      }
    }
  },
  "en": {
    "html": {
      "title": "B1 LV→EN: Match Rush + Prefix Forge"
    },
    "badge": "Week 1",
    "gameTitle": "LV→EN Word Games (B1)",
    "buttons": {
      "modeMatch": "▶ Match Rush",
      "modeForge": "▶ Prefix Forge",
      "practice": "Practice",
      "challenge": "Challenge",
      "prevAria": "Previous card",
      "nextAria": "Next card",
      "deckSizeAria": "Toggle deck size",
      "deckSizeTitle": "Toggle deck size",
      "export": "Export Results (CSV)",
      "exportAria": "Export results as CSV",
      "help": "Help",
      "helpAria": "Help"
    },
    "labels": {
      "loading": "Loading...",
      "loadError": "Failed to load data.",
      "legend": "<b>Controls:</b> Mouse clicks. — <span class=\"kbd\">H</span> help, <span class=\"kbd\">R</span> restart round, <span class=\"kbd\">1</span> Match, <span class=\"kbd\">2</span> Forge, <span class=\"kbd\">D</span> deck size. <br/>📏 = Fit screen (no scroll), 📜 = Full deck (scroll if needed). LV→EN only.",
      "languageSelect": "Choose language",
      "controls": "Game controls",
      "gameState": "Game state"
    },
    "status": {
      "ready": "Ready. Choose a mode.",
      "practice": "Practice mode",
      "challenge": "Challenge mode (Match = ♥♥♥)",
      "fit": "Fit to screen mode",
      "full": "Full deck mode (scrollable)"
    },
    "deckSize": {
      "titleAuto": "Switch to full deck (scrollable)",
      "titleFull": "Switch to fit screen (no scroll)"
    },
    "help": {
      "title": "Help",
      "close": "Close",
      "lines": [
        "▶ MATCH RUSH — Click the pair: first LV word, then its EN meaning.",
        "Mistakes in practice show a brief hint (e.g., -ties = reflexive).",
        "Challenge mode has a timer and hearts.",
        "",
        "📏 Deck Size — Toggle between 'fit screen' (no scrolling)",
        "and 'full deck' (scroll, more words).",
        "",
        "▶ PREFIX FORGE — Add the correct prefix to the verb root",
        "(e.g., __mainīt → izmainīt) based on the given EN meaning.",
        "",
        "Shortcuts: [1] Match, [2] Forge, [H] help, [R] restart, [D] deck size."
      ]
    },
    "endingsBuilder": {
      "title": "Endings Builder",
      "subtitle": "Drop the correct ending to complete the word.",
      "buttons": {
        "check": "Check (Enter)",
        "next": "Next (N)",
        "rule": "Show rule",
        "ruleHide": "Hide rule",
        "report": "Report error"
      },
      "labels": {
        "score": "Score",
        "streak": "Streak",
        "strict": "Strict diacritics",
        "answer": "Type the full form",
        "keypad": "Latvian letters",
        "options": "Endings",
        "dropPlaceholder": "Drop ending",
        "ruleTitle": "Rule table",
        "case": "Case",
        "number": "Number",
        "columns": {
          "SG": "Singular",
          "PL": "Plural",
          "SG_M": "SG masc",
          "SG_F": "SG fem",
          "PL_M": "PL masc",
          "PL_F": "PL fem"
        }
      },
      "feedback": {
        "correct": "Correct!",
        "incorrect": "Wrong — check the rule.",
        "fallback": "Accepted without diacritics. Enable strict mode to practise marks."
      },
      "icons": {
        "correct": "✔️",
        "incorrect": "✖️",
        "info": "ℹ️"
      },
      "announce": {
        "correct": "Correct ending placed.",
        "incorrect": "Wrong ending. Try again."
      },
      "explain": {
        "prefix": "⇒"
      },
      "strictMode": {
        "on": "Strict mode enabled.",
        "off": "Strict mode disabled."
      },
      "reportTemplate": "### What happened?\n\nDescribe the incorrect ending or rule.\n\n### Context\n- Stem: (fill in)\n- Case/number: (fill in)\n- Device/browser: \n",
      "cases": {
        "NOM": "Nominative",
        "GEN": "Genitive",
        "DAT": "Dative",
        "ACC": "Accusative",
        "LOC": "Locative",
        "VOC": "Vocative"
      }
    }
  },
  "ru": {
    "html": {
      "title": "B1 LV→RU: Match Rush + Prefix Forge"
    },
    "badge": "Неделя 1",
    "gameTitle": "LV→RU Слова (B1)",
    "buttons": {
      "modeMatch": "▶ Match Rush",
      "modeForge": "▶ Prefix Forge",
      "practice": "Практика",
      "challenge": "Игра",
      "prevAria": "Предыдущая карточка",
      "nextAria": "Следующая карточка",
      "deckSizeAria": "Переключить размер колоды",
      "deckSizeTitle": "Переключить размер колоды",
      "export": "Экспорт результатов (CSV)",
      "exportAria": "Экспортировать результаты в CSV",
      "help": "Помощь",
      "helpAria": "Помощь"
    },
    "labels": {
      "loading": "Загрузка...",
      "loadError": "Не удалось загрузить данные.",
      "legend": "<b>Управление:</b> клики мышью. — <span class=\"kbd\">H</span> помощь, <span class=\"kbd\">R</span> заново, <span class=\"kbd\">1</span> Match, <span class=\"kbd\">2</span> Forge, <span class=\"kbd\">D</span> размер колоды. <br/>📏 = Под экран (без прокрутки), 📝 = Полная колода (с прокруткой).",
      "languageSelect": "Выберите язык",
      "controls": "Элементы управления",
      "gameState": "Состояние игры"
    },
    "status": {
      "ready": "Готово. Выберите режим.",
      "practice": "Режим практики",
      "challenge": "Режим вызова (Match = ♥♥♥)",
      "fit": "Режим под экран",
      "full": "Режим полной колоды (прокрутка)"
    },
    "deckSize": {
      "titleAuto": "Переключить на полную колоду (прокрутка)",
      "titleFull": "Переключить на размер по экрану (без прокрутки)"
    },
    "help": {
      "title": "Помощь",
      "close": "Закрыть",
      "lines": [
        "▶ MATCH RUSH — Сначала щёлкните LV слово, затем его значение.",
        "Ошибки в практике показывают подсказку (напр., -ties = возвратный).",
        "В режиме вызова есть таймер и сердца.",
        "",
        "📏 Размер колоды — Переключение между 'под экран' (без прокрутки)",
        "и 'полная колода' (с прокруткой, больше слов).",
        "",
        "▶ PREFIX FORGE — Добавьте правильный префикс к корню глагола",
        "(напр., __mainīt → izmainīt) по данному значению.",
        "",
        "Сочетания клавиш: [1] Match, [2] Forge, [H] помощь, [R] заново, [D] размер."
      ]
    },
    "endingsBuilder": {
      "title": "Конструктор окончаний",
      "subtitle": "Перетащите правильное окончание, чтобы завершить слово.",
      "buttons": {
        "check": "Проверить (Enter)",
        "next": "Далее (N)",
        "rule": "Показать правило",
        "ruleHide": "Скрыть правило",
        "report": "Сообщить об ошибке"
      },
      "labels": {
        "score": "Счёт",
        "streak": "Серия",
        "strict": "Строгий режим",
        "answer": "Введите полную форму",
        "keypad": "Латышские буквы",
        "options": "Окончания",
        "dropPlaceholder": "Перетащите окончание",
        "ruleTitle": "Таблица правил",
        "case": "Падеж",
        "number": "Число",
        "columns": {
          "SG": "Единств.",
          "PL": "Множеств.",
          "SG_M": "Ед. м.",
          "SG_F": "Ед. ж.",
          "PL_M": "Мн. м.",
          "PL_F": "Мн. ж."
        }
      },
      "feedback": {
        "correct": "Верно!",
        "incorrect": "Неверно — посмотрите правило.",
        "fallback": "Принято без диакритики. Включите строгий режим для тренировки знаков."
      },
      "icons": {
        "correct": "✔️",
        "incorrect": "✖️",
        "info": "ℹ️"
      },
      "announce": {
        "correct": "Окончание выбрано правильно.",
        "incorrect": "Неверное окончание. Попробуйте снова."
      },
      "explain": {
        "prefix": "⇒"
      },
      "strictMode": {
        "on": "Строгий режим включён.",
        "off": "Строгий режим отключён."
      },
      "reportTemplate": "### Что произошло?\n\nОпишите неверное окончание или правило.\n\n### Контекст\n- Основа: (впишите)\n- Падеж/число: (впишите)\n- Устройство/браузер: \n",
      "cases": {
        "NOM": "Именительный",
        "GEN": "Родительный",
        "DAT": "Дательный",
        "ACC": "Винительный",
        "LOC": "Местный",
        "VOC": "Звательный"
      }
    }
  }
});
